### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Jharr20210609** [microsoft/msix-packaging#456]
*Project*
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

**Describe the bug**
```
"D:\a\1\s\ProjectName1_Production.sln" (default target) (1) ->
"D:\a\1\s\ProjectName1.MsixInstaller\ProjectName1.MsixInstaller.wapproj" (default target) (5) ->
(GenerateAppInstallerFileForPackage target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\ProjectName1.MsixInstaller\AppPackages\ProjectName1.MsixInstaller_x64.appinstaller'. [D:\a\1\s\ProjectName1.MsixInstaller\ProjectName1.MsixInstaller.wapproj]

    26 Warning(s)
    1 Error(s)

```

**To Reproduce**
I followed the instructions per this website and I am getting the following error on the MSIX build and package task:

**Expected behavior**
The task should complete successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/85651174/121438041-edd63980-c948-11eb-98a9-4382c4be6382.png)
![image](https://user-images.githubusercontent.com/85651174/121438094-06deea80-c949-11eb-8284-bdfd929016c2.png)

**Platform**
Windows-2019

**Additional context**
I am not sure why this is trying to find the appinstaller file during the MSIX build stage.

**Full Pipeline YAML**

pool:
  name: Azure Pipelines
  demands: msbuild
```

#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'
  inputs:
    versionSpec: 5.9.1
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'ProjectName1_Production.sln'

- task: MSIX.msix-ci-automation-task.msix-packaging.MsixPackaging@1
  displayName: 'MSIX build and package'
  inputs:
    outputPath: '$(Build.ArtifactStagingDirectory)\ProjectName1.msix'
    solution: 'ProjectName1_Production.sln'
    buildPlatform: x64
    updateAppVersion: true
    manifestFile: ProjectName1.MsixInstaller/Package.appxmanifest
    appPackageDistributionMode: SideloadOnly
    msbuildArchitecture: x64

- task: MSIX.msix-ci-automation-task.msix-signing.MsixSigning@1
  displayName: 'Sign MSIX package'
  inputs:
    certificate: 'Accumatch.DeveloperCodeSigningCert_TemporaryKey.pfx'
    passwordVariable: signingCert.password

- task: MSIX.msix-ci-automation-task.app-installer-file.AppInstallerFile@1
  displayName: 'Create App Installer file'
  inputs:
    package: '$(Build.ArtifactStagingDirectory)\ProjectName1.msix'
    outputPath: '$(Build.ArtifactStagingDirectory)\ProjectName1.appinstaller'
    uri: 'https://ProjectName1demo.azurewebsites.net/ProjectName1.appinstaller'
    mainItemUri: 'https://ProjectName1demo.azurewebsites.net/ProjectName1.msix'
    showPromptWhenUpdating: true
    updateBlocksActivation: true

- task: MSIX.msix-ci-automation-task.msix-app-attach.MsixAppAttach@1
  displayName: 'Create package for MSIX app attach'
  inputs:
    package: '$(Build.ArtifactStagingDirectory)\ProjectName1.msix'
    vhdxOutputPath: '$(Build.ArtifactStagingDirectory)\ProjectName1.vhdx'
    vhdxSize: 200

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**\bin\**\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


```
