### ISSUE TITLE
[ENHANCEMENT] Is it possible customize the configuration builds?

### ISSUE THREAD

**Issue by Jharr20210609** [microsoft/msix-packaging#458]
I have an Azure build pipeline that is using the `MSIX Packaging` suite of packages from Microsoft, which can be found [Here](https://marketplace.visualstudio.com/items?itemName=MSIX.msix-ci-automation-task).

I am configuring the `MSIX build and package task` and in it there is a drop down menu for the `Configuration`, which only contains options for `debug` and `release`. 

![image](https://user-images.githubusercontent.com/85651174/121591827-91822100-c9ff-11eb-832b-ef2eb2e7b98c.png)

However, we only have build configurations for `debug`, `demo`, `development`, and `production` and we are using SlowCheetah to identify which `appsettings.<environment>.json` file to use. So, we need to be able to add these additional build configurations so that the correct `appsettings.json` file is used. How can we add these build configurations?

**Comment by Jharr20210609** [comment]
**The contents of the .wapproj file are as follows:
Note: I have replaced the actual thumbprint with AThumbPrint**

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' &lt; '15.0'">
    <VisualStudioVersion>15.0</VisualStudioVersion>
  </PropertyGroup>
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Demo|x64">
      <Configuration>Demo</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Development|x64">
      <Configuration>Development</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Production|x64">
      <Configuration>Production</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup>
    <WapProjPath Condition="'$(WapProjPath)'==''">$(MSBuildExtensionsPath)\Microsoft\DesktopBridge\</WapProjPath>
  </PropertyGroup>
  <Import Project="$(WapProjPath)\Microsoft.DesktopBridge.props" />
  <PropertyGroup>
    <ProjectGuid>6252bba9-ef8e-4b89-96b2-d02271c8652e</ProjectGuid>
    <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <DefaultLanguage>en-US</DefaultLanguage>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <PackageCertificateThumbprint>_AThumbPrint_</PackageCertificateThumbprint>
    <GenerateAppInstallerFile>True</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
    <AppInstallerUri>https://ProjectName1demo.azurewebsites.net</AppInstallerUri>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <EntryPointProjectUniqueName>..\ProjectName1\ProjectName1.csproj</EntryPointProjectUniqueName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Demo|x64'">
    <AppxBundle>Never</AppxBundle>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Production|x64'">
    <AppxBundle>Never</AppxBundle>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <AppxBundle>Never</AppxBundle>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Development|x64'">
    <AppxBundle>Never</AppxBundle>
  </PropertyGroup>
  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest">
      <SubType>Designer</SubType>
    </AppxManifest>
  </ItemGroup>
  <Import Project="$(WapProjPath)\Microsoft.DesktopBridge.targets" />
  <ItemGroup>
    <Content Include="Package.appinstaller" />
    <Content Include="Images\BadgeLogo.scale-100.png" />
    <Content Include="Images\BadgeLogo.scale-125.png" />
    <Content Include="Images\BadgeLogo.scale-150.png" />
    <Content Include="Images\BadgeLogo.scale-200.png" />
    <Content Include="Images\BadgeLogo.scale-400.png" />
    <Content Include="Images\LargeTile.scale-100.png" />
    <Content Include="Images\LargeTile.scale-125.png" />
    <Content Include="Images\LargeTile.scale-150.png" />
    <Content Include="Images\LargeTile.scale-200.png" />
    <Content Include="Images\LargeTile.scale-400.png" />
    <Content Include="Images\SmallTile.scale-100.png" />
    <Content Include="Images\SmallTile.scale-125.png" />
    <Content Include="Images\SmallTile.scale-150.png" />
    <Content Include="Images\SmallTile.scale-200.png" />
    <Content Include="Images\SmallTile.scale-400.png" />
    <Content Include="Images\SplashScreen.scale-100.png" />
    <Content Include="Images\SplashScreen.scale-125.png" />
    <Content Include="Images\SplashScreen.scale-150.png" />
    <Content Include="Images\SplashScreen.scale-200.png" />
    <Content Include="Images\SplashScreen.scale-400.png" />
    <Content Include="Images\Square150x150Logo.scale-100.png" />
    <Content Include="Images\Square150x150Logo.scale-125.png" />
    <Content Include="Images\Square150x150Logo.scale-150.png" />
    <Content Include="Images\Square150x150Logo.scale-200.png" />
    <Content Include="Images\Square150x150Logo.scale-400.png" />
    <Content Include="Images\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
    <Content Include="Images\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
    <Content Include="Images\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
    <Content Include="Images\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
    <Content Include="Images\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
    <Content Include="Images\Square44x44Logo.altform-unplated_targetsize-16.png" />
    <Content Include="Images\Square44x44Logo.altform-unplated_targetsize-24.png" />
    <Content Include="Images\Square44x44Logo.altform-unplated_targetsize-256.png" />
    <Content Include="Images\Square44x44Logo.altform-unplated_targetsize-32.png" />
    <Content Include="Images\Square44x44Logo.altform-unplated_targetsize-48.png" />
    <Content Include="Images\Square44x44Logo.scale-100.png" />
    <Content Include="Images\Square44x44Logo.scale-125.png" />
    <Content Include="Images\Square44x44Logo.scale-150.png" />
    <Content Include="Images\Square44x44Logo.scale-200.png" />
    <Content Include="Images\Square44x44Logo.scale-400.png" />
    <Content Include="Images\Square44x44Logo.targetsize-16.png" />
    <Content Include="Images\Square44x44Logo.targetsize-24.png" />
    <Content Include="Images\Square44x44Logo.targetsize-256.png" />
    <Content Include="Images\Square44x44Logo.targetsize-32.png" />
    <Content Include="Images\Square44x44Logo.targetsize-48.png" />
    <Content Include="Images\StoreLogo.scale-100.png" />
    <Content Include="Images\StoreLogo.scale-125.png" />
    <Content Include="Images\StoreLogo.scale-150.png" />
    <Content Include="Images\StoreLogo.scale-200.png" />
    <Content Include="Images\StoreLogo.scale-400.png" />
    <Content Include="Images\Wide310x150Logo.scale-100.png" />
    <Content Include="Images\Wide310x150Logo.scale-125.png" />
    <Content Include="Images\Wide310x150Logo.scale-150.png" />
    <Content Include="Images\Wide310x150Logo.scale-200.png" />
    <Content Include="Images\Wide310x150Logo.scale-400.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectName1\ProjectName1.csproj">
      <SkipGetTargetFrameworkProperties>True</SkipGetTargetFrameworkProperties>
    </ProjectReference>
  </ItemGroup>
</Project>

**Comment by Jharr20210609** [comment]
I am attempting to see if I can work around this issue by converting the pipeline to YAML (from classic). However, the MSIX Signing task is not able to retrieve the password from the variable-group's secret variable value that is assigned to `SigningCertPassword`. Note, the pipeline in Classic mode is able to retrieve this variables value. Here is the YAML that I have for the MSIX signing task.

```
variables:
- name: solution
  value: 'AccuTax_Production.sln'
- name: buildPlatform
  value: 'x64'
- name: buildConfiguration
  value: 'demo'
- name: vhdxSize
  value: '200'
- group: 'legacy-pipeline'
- name: SigningCertPassword1
  value: $[variables.SigningCertPassword]


steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.9.1'
    checkLatest: true
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: $(solution)
    feedsToUse: 'select'
- task: MsixPackaging@1
  inputs:
    outputPath: '$(Build.ArtifactStagingDirectory)\AccuTax.msix'
    solution: $(solution)
    clean: true
    generateBundle: false
    buildConfiguration: $(buildConfiguration)
    buildPlatform: $(buildPlatform)
    updateAppVersion: false
    appPackageDistributionMode: 'SideloadOnly'
    msbuildLocationMethod: 'version'
    msbuildVersion: 'latest'
    msbuildArchitecture: $(buildPlatform)
- task: MsixSigning@1
  inputs:
    package: '$(Build.ArtifactStagingDirectory)\**\*.msix*'
    certificate: 'Accumatch.DeveloperCodeSigningCert_TemporaryKey.pfx'
    passwordVariable: $(SigningCertPasswordNew)
- task: AppInstallerFile@1
  inputs:
    package: '$(Build.ArtifactStagingDirectory)\AccuTax.msix'
    outputPath: '$(Build.ArtifactStagingDirectory)\AccuTax.appinstaller'
    method: 'create'
    fileVersion: '1.0.0.0'
    uri: 'https://accutaxdemo.azurewebsites.net/AccuTax.appinstaller'
    mainItemUri: 'https://accutaxdemo.azurewebsites.net/AccuTax.msix'
    showPromptWhenUpdating: true
    updateBlocksActivation: true
- task: MsixAppAttach@1
  inputs:
    package: '$(Build.ArtifactStagingDirectory)\AccuTax.msix'
    vhdxOutputPath: '$(Build.ArtifactStagingDirectory)\AccuTax.vhdx'
    vhdxSize: $(vhdxSize)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
```

Error: '##[error]The secret variable given does not point to a valid password.'
