### ISSUE TITLE
Cannot find generated appinstaller file when using AppInstallerFile task

### ISSUE THREAD

**Issue by tripleacoder** [microsoft/msix-packaging#462]
I am trying to use the AppInstallerFile task instead of MSBuild to create an .appinstaller file. The reason is that MSBuild creates the file using an outdated schema (2017) which makes auto-updates not work very well.

Is this a good idea?

I have added the following YAML to my build template. It runs without errors, but I cannot see where the .appinstaller file is located that it is supposed to create. It does not get uploaded to Artifacts with the rest of the MSIX package.
The log output only says that an msix has been extracted.
If I list the contents of the temp folder, it does not show the files that were supposed to have been extracted.

Here is the YAML as well as the task output:

```
    - task: AppInstallerFile@1
      inputs:
        package: '$(Build.BinariesDirectory)\$(channelName)\${{ parameters.installerProjectName }}\AppPackages\${{ parameters.packageName }}_$(newVersion)\${{ parameters.installerProjectName }}_$(newVersion)_x64.msixbundle'
        outputPath: '$(Build.BinariesDirectory)/$(channelName)\${{ parameters.installerProjectName }}.appinstaller'
        method: 'create'
        fileVersion: $(newVersion)
        uri: '$(msixInstallUrl)$(channelName)\${{ parameters.installerProjectName }}.appinstaller'
        mainItemUri: '$(msixInstallUrl)$(channelName)'
        hoursBetweenUpdateChecks: '0'
        showPromptWhenUpdating: true
        updateBlocksActivation: true
```

Starting: AppInstallerFile

Task         : App Installer file for MSIX
Description  : Create or update an App Installer file for MSIX apps
Version      : 1.1.1
Author       : Microsoft Corporation
Help         : https://aka.ms/msix-cicd

D:\a\_tasks\AppInstallerFile_ced3bc79-ea98-4c51-8a83-ed4e3a0a77ed\1.1.1\node_modules\common\lib\makeappx.exe unbundle -p D:\a\1\b\Test\MyApp.Installer\AppPackages\MyApp_2021.628.752.771\MyApp.Installer_2021.628.752.771_x64.msixbundle -d D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64 -o
Microsoft (R) MakeAppx Tool

Copyright (C) 2013 Microsoft.  All rights reserved.

The path (/p) parameter is: "\\?\D:\a\1\b\Test\MyApp.Installer\AppPackages\MyApp_2021.628.752.771\MyApp.Installer_2021.628.752.771_x64.msixbundle"

The output directory (/d) parameter is: "\\?\D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64"

Extracting file AppxMetadata\AppxBundleManifest.xml to \\?\D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64\AppxMetadata\AppxBundleManifest.xml

Extracting file AppxBlockMap.xml to \\?\D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64\AppxBlockMap.xml

Extracting file AppxSignature.p7x to \\?\D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64\AppxSignature.p7x

Extracting file MyApp.Installer_2021.628.752.771_x64.msix to \\?\D:\a\\_temp\MyApp.Installer_2021.628.752.771_x64\MyApp.Installer_2021.628.752.771_x64.msix

Bundle extraction succeeded.

Finishing: AppInstallerFile

Contents of temp folder:

"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\\_temp\14c717bc-908a-48fe-9d6f-6367c4f31313.ps1'"

    Directory: D:\a\_temp

Mode                LastWriteTime         Length Name                                              
-a----        6/28/2021   8:00 AM             36 .taskkey                                                              
-a----        6/28/2021   8:00 AM            332 14c717bc-908a-48fe-9d6f-6367c4f31313.ps1                              
-a----        6/28/2021   7:57 AM            839 4702a2df-f863-4e30-b15f-2e799e206255.ps1                              
-a----        6/28/2021   8:00 AM            330 647d3898-80c3-4c77-b8a2-022f04c06899.ps1                              
-a----        6/28/2021   7:57 AM           5483 MyCompanyCert-sha1.p12
